name: Test zenn-editor

on:
  pull_request:
    branches:
      - main
      - canary
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn build
      - name: Run tests for zenn-markdown-html
        run: yarn test
        working-directory: packages/zenn-markdown-html
      - name: Run tests for zenn-cli
        run: yarn test
        working-directory: packages/zenn-cli
